# Generated by Django 5.1.6 on 2025-02-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=3)),
                ('atomic_number', models.PositiveIntegerField()),
                ('atomic_weight', models.FloatField()),
                ('density', models.FloatField()),
                ('melting_point', models.FloatField()),
                ('boiling_point', models.FloatField()),
                ('phase', models.CharField(max_length=50)),
            ],
        ),
    ]
