# Generated by Django 5.1.6 on 2025-02-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_chemical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_weight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='boiling_point',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='element',
            name='density',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='melting_point',
            field=models.CharField(max_length=20),
        ),
    ]
