# Generated by Django 5.1.6 on 2025-02-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_chemical', '0002_element_group_element_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.CharField(choices=[('noble gas', 'Noble Gas'), ('alkali metal', 'Alkali Metal'), ('alkaline earth metal', 'Alkaline Earth Metal'), ('metalloid', 'Metalloid'), ('halogen', 'Halogen'), ('transition metal', 'Transition Metal'), ('post-transition metal', 'Post-Transition Metal'), ('lanthanide', 'Lanthanide'), ('actinide', 'Actinide'), ('non metal', 'Non Metal')], default='alkali metal', max_length=50),
        ),
    ]
